#!/bin/bash

monitors=($(xrandr --query | grep " connected" | awk '{print $1}' | sort -r))
workspaces_config="$HOME/.config/i3/_monitors.conf"

primary_monitor=""
second_monitor=""
third_monitor=""

function push_monitor() {
    local curr_monitor=$1

    if [ ! -z "$primary_monitor" ]; then
        if [ -z "$second_monitor" ]; then
            third_monitor=$second_monitor
        fi
        second_monitor=$primary_monitor
    fi

    primary_monitor=$curr_monitor
}

function unshift_monitor() {
    local curr_monitor=$1

    if [ -z "$primary_monitor" ]; then
        primary_monitor=$curr_monitor
    elif [ -z "$second_monitor" ]; then
        second_monitor=$curr_monitor
    else
        third_monitor=$curr_monitor
    fi
}

monitor_count=${#monitors[@]}

xrandr_cmd="xrandr"

for monitor in "${monitors[@]}"
do
    if [[ "$monitor" == *"eDP"* ]]; then
        unshift_monitor "$monitor"
        xrandr_cmd="$xrandr_cmd --output $monitor --auto --primary"
    else
        push_monitor "$monitor"
        xrandr_cmd="$xrandr_cmd --output $monitor --auto"
    fi
done

eval "$xrandr_cmd"

declare -A workspaces=(
    ["1:main"]="1,1,1"
    ["1:steam"]="1,1,1"
    ["2:web"]="1,1,1"
    ["3:chat"]="1,2,2"
    ["3:game"]="1,1,1"
    ["4:aux"]="1,1,1"
    ["5:jobs"]="1,2,1"
    ["5:stream"]="1,2,3"
    ["6:git"]="1,1,1"
    ["6:ps"]="1,2,2"
)

echo "# automatic generated by 'monitors_and_workspaces.sh'" > "$workspaces_config"

idx=$monitor_count
if [ "$idx" -gt 3 ]; then idx=3; fi

for ws in "${!workspaces[@]}"; do
    preferred_monitor_idx=$(echo "${workspaces[$ws]}" | cut -f $idx -d ",")

    case "$preferred_monitor_idx" in
        1) preferred_monitor=$primary_monitor ;;
        2) preferred_monitor=$second_monitor ;;
        *) preferred_monitor=$third_monitor ;;
    esac

    echo "Settings $ws on monitor $preferred_monitor..."

    echo "workspace \"$ws\" output $preferred_monitor" >> "$workspaces_config"
    i3-msg "[workspace=\"$ws\"] move workspace to output $preferred_monitor" > /dev/null 2>&1 || true
done

i3-msg "reload" > /dev/null 2>&1 || true
