#!/bin/bash

function crash_gpu_collector() {
    sudo -v || { echo "This script requires sudo privileges to read kernel logs."; exit 1; }

    OUT_DIR="$HOME/.crash"
    mkdir -p "$OUT_DIR"
    TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
    OUT_FILE="$OUT_DIR/${TIMESTAMP}.crash-log.md"

    echo "Collecting system state and logs into $OUT_FILE..."

    echo "# System Crash Report - $TIMESTAMP" > "$OUT_FILE"
    echo "*Generated by Crash Collector Script*" >> "$OUT_FILE"

    add_section() {
        local TITLE="$1"
        local COMMAND="$2"
        echo -e "\n## $TITLE\n" >> "$OUT_FILE"
        echo '```text' >> "$OUT_FILE"
        # Run command, append output, redirect stderr to /dev/null to keep it clean
        eval "$COMMAND" >> "$OUT_FILE" 2>/dev/null || echo "[!] Command failed or file not found." >> "$OUT_FILE"
        echo '```' >> "$OUT_FILE"
    }

    # --- System & Kernel ---
    add_section "System Information" "uname -a && echo '---' && cat /etc/os-release"
    add_section "Current Kernel Parameters" "cat /proc/cmdline"
    add_section "Bootloader Configs (systemd-boot)" "cat /boot/loader/loader.conf && echo '---' && cat /boot/loader/entries/*.conf"

    # --- Hardware & GPU State ---
    add_section "GPU Identification" "lspci -nn | /bin/grep -i vga"
    add_section "PCIe Link & Resizable BAR Status" "sudo dmesg | /bin/grep -iE 'pcie.*link|bar|aspm'"
    add_section "AMDGPU Module Parameters" "for f in /sys/module/amdgpu/parameters/*; do echo \"\$(basename \$f): \$(cat \$f 2>/dev/null)\"; done"

    # --- Hyprland ---
    # TODO: improve
    add_section "Pertinent Hyprland Configs" "cat ~/.config/hypr/_looks.conf ~/.config/hypr/_monitors.conf ~/.config/hypr/_xwayland_prefs.conf ~/.config/hypr/_input.conf"
    add_section "Latest Hyprland Crash Report" "/bin/ls -t ~/.cache/hyprland/hyprlandCrashReport*.txt 2>/dev/null | head -n 1 | xargs cat"

    # --- Persistent Logs (The Golden Clues) ---
    add_section "Previous Boot: Last 100 Kernel Messages (The Freeze)" "sudo journalctl -k -b -1 | tail -n 100"
    add_section "Previous Boot: All AMDGPU Driver Logs" "sudo journalctl -k -b -1 | /bin/grep -i amdgpu"
    add_section "Current Boot: AMDGPU Warnings & Errors" "sudo journalctl -k -b 0 | /bin/grep -iE 'amdgpu.*(error|fault|timeout|reset|fail)'"

    echo "Collection complete! File saved to: $OUT_FILE"
}
