[window]
decorations = "Full"
padding.x = 10
padding.y = 10
opacity = 0.9

[font]
normal.family = "Fira Code Nerd Font"
normal.style = "Regular"

bold.family = "Fira Code Nerd Font"
bold.style = "Bold"

italic.family = "Fira Code Nerd Font"
italic.style = "Italic"

size = 14.0

