bindsym $mod+Return exec --no-startup-id $TERMINAL

bindsym $mod+space exec --no-startup-id rofi -i -matching fuzzy -show drun -theme ~/.config/rofi/config.rasi
bindsym $mod+Up fullscreen toggle
# TODO: $notifications = swaync-client -t -sw
# TODO:  $file_manager = bash ~/.config/hypr/scripts/special_ws_file_manager.sh
bindsym $mod+w kill
bindsym $mod+Shift+w exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

bindsym $mod+q workspace $ws_web; exec --no-startup-id $BROWSER -P default
bindsym $mod+b exec --no-startup-id bash $HOME/.config/hypr/scripts/bookmarks.sh
bindsym $mod+m exec --no-startup-id "$HOME/.config/i3/script/floating_mixer.sh"
bindsym $mod+c exec --no-startup-id "$HOME/.config/i3/script/floating_calc.sh"
bindsym $mod+t exec --no-startup-id "$HOME/.config/i3/script/floating_scratchpad.sh"
bindsym $mod+o exec --no-startup-id "$HOME/.config/i3/script/floating_notes.sh"
bindsym $mod+v exec --no-startup-id copyq toggle
bindsym Print exec --no-startup-id flameshot gui

bindsym $mod+1 workspace $ws_main
bindsym $mod+2 workspace $ws_web
bindsym $mod+3 workspace $ws_chat
bindsym $mod+4 workspace $ws_aux
bindsym $mod+5 workspace $ws_jobs
bindsym $mod+6 workspace $ws_git

# TODO: magnifier
# TODO: move to workspace
# TODO: file manager
# TODO: color_picker

# TODO: bind = SUPER, Escape, exec, hyprlock

floating_modifier $mod

bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

bindsym $mod+Tab focus right
bindsym $mod+Shift+Tab focus left

bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

bindsym $mod+e layout toggle split

# TODO: Move/resize windows with mainMod + LMB/RMB and dragging
# bindm = SUPER, mouse:272, movewindow
# bindm = SUPER, mouse:273, resizewindow

# TODO: test
set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && $refresh_i3status
bindsym XF86MonBrightnessUp exec --no-startup-id brightnessctl s 10%+
bindsym XF86MonBrightnessDown exec --no-startup-id brightnessctl s 10%-

# TODO: 
# bindsym XF86AudioNext exec --no-startup-id playerctl next
# bindsym XF86AudioPause exec --no-startup-id playerctl play-pause
# bindsym XF86AudioPlay exec --no-startup-id playerctl play-pause
# bindsym XF86AudioPrev exec --no-startup-id playerctl previous

# reload the configuration file
bindsym $mod+r exec --no-startup-id $HOME/.config/i3/script/monitors_and_workspaces.sh
bindsym $mod+Shift+r reload

