
font pango:Fira Code Nerd Font 10

default_border pixel 1
default_floating_border pixel 1

gaps inner 5
gaps outer 10

# TODO: # Start i3bar to display a workspace bar (plus the system information i3status
# # finds out, if available)
# bar {
#         status_command i3status
# }

    # TODO:
    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    # col.active_border = rgba(65bcffee) rgba(fca7eaee) 90deg
    # col.inactive_border = rgba(1e2030aa)

    # resize_on_border = false

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    # allow_tearing = false

    # layout = master

# TODO: TABS layout

# group {
#     groupbar {
#         render_titles = true
#         height = 28
#         col.active = rgba(1e2030ff)     # Active tab
#         col.inactive = rgba(22243688)   # Inactive tabs
#
#         font_family = Fira Code Nerd Font
#         font_size = 16
#         text_color = rgba(c8d3f5ff)
#
#         gradients = true
#         gradient_rounding = 15
#         gradient_round_only_edges = false
#
#         indicator_height = 0
#         priority = 0
#
#         gaps_in = 20
#         gaps_out = 5
#     }
#
#     col.border_active = rgba(65bcffee) rgba(fca7eaee) 90deg
#     col.border_inactive = rgba(1e2030aa)
# }
