
font pango:Fira Code Nerd Font 10

gaps inner 5
gaps outer 10

title_align center

default_border pixel 2
default_floating_border pixel 2

for_window [class=".*"] title_format "  <b>%class</b>  <span alpha='60%'>%title</span>"
for_window [all] title_window_icon on

set $bg_active      #1e2030ff
set $bg_inactive    #22243688
set $text           #c8d3f5ff
set $border_active  #65bcffee
set $border_pink    #fca7eaee
set $border_inactive #1e2030aa

# class                  border           background      text      indicator        child_border
client.focused           $border_active   $bg_active      $text     $border_pink     $border_active
client.focused_inactive  $border_inactive $bg_inactive    $text     $border_inactive $border_inactive
client.unfocused         $border_inactive $bg_inactive    $text     $border_inactive $border_inactive
client.urgent            #ff757fff       #ff757fff       #ffffff   #ff757fff       #ff757fff
client.placeholder       #00000000       #1e2030ff       $text     #00000000       #1e2030ff
client.background        #1e2030ff

