# NOTE: this file will be overwritten by `monitors_and_workspaces.sh`

set $ws_main   "main"
set $ws_web    "web"
set $ws_log    "log"
set $ws_chat   "chat"
set $ws_aux    "aux"
set $ws_jobs   "jobs"
set $ws_media  "media"
set $ws_game   "game"
set $ws_stream "stream"
set $ws_docs   "docs"
set $ws_steam  "steam"
set $ws_git    "git"
