# NOTE: this file will be overwritten by `monitors_and_workspaces.sh`

set $ws_main   "1:main"
set $ws_steam  "1:steam"
set $ws_web    "2:web"
set $ws_game   "3:game"
set $ws_chat   "3:chat"
set $ws_aux    "4:aux"
set $ws_jobs   "5:jobs"
set $ws_stream "5:stream"
set $ws_git    "6:git"
set $ws_ps     "6:ps"
