services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=$server_uid
      - PGID=$media_server_gid
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - 1337:8080
    volumes:
      - /home/server/.config/qbittorrent:/config
      - $storage/qbittorrent/downloads:/downloads
    restart: unless-stopped

  jellyfin:
    # NOTE: media data server
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=$server_uid
      - PGID=$media_server_gid
      - TZ=America/Sao_Paulo
    volumes:
      - /home/server/.config/jellyfin:/config
      - $storage/qbittorrent/downloads:/downloads
      # - $storage/radarr/movies:/data/movies
      # - $storage/sonarr/tv:/data/tvshows
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped

  # radarr:
  #   # NOTE: manages movies
  #   image: lscr.io/linuxserver/radarr:latest
  #   container_name: radarr
  #   environment:
  #     - PUID=$server_uid
  #     - PGID=$media_server_gid
  #     - TZ=America/Sao_Paulo
  #   ports:
  #     - 7878:7878
  #   volumes:
  #     - /home/server/.config/radarr:/config
  #     - $storage/qbittorrent/downloads:/downloads
  #     - $storage/radarr/movies:/movies
  #   restart: unless-stopped

  # sonarr:
  #   # NOTE: manages tv shows
  #   image: lscr.io/linuxserver/sonarr:latest
  #   container_name: sonarr
  #   environment:
  #     - PUID=$server_uid
  #     - PGID=$media_server_gid
  #     - TZ=America/Sao_Paulo
  #   ports:
  #     - 8989:8989
  #   volumes:
  #     - /home/server/.config/sonarr:/config
  #     - $storage/qbittorrent/downloads:/downloads
  #     - $storage/sonarr/tv:/tv
  #   restart: unless-stopped
  #
  # bazarr:
  #   # NOTE: manages subtitles
  #   image: lscr.io/linuxserver/bazarr:latest
  #   container_name: bazarr
  #   environment:
  #     - PUID=$server_uid
  #     - PGID=$media_server_gid
  #     - TZ=America/Sao_Paulo
  #   volumes:
  #     - /home/server/.config/bazarr:/config
  #     - $storage/radarr/movies:/movies
  #     - $storage/sonarr/tv:/tv
  #   restart: unless-stopped
  #
  # prowlarr:
  #   # NOTE: media indexer
  #   image: lscr.io/linuxserver/prowlarr:latest
  #   container_name: prowlarr
  #   environment:
  #     - PUID=$server_uid
  #     - PGID=$media_server_gid
  #     - TZ=America/Sao_Paulo
  #   volumes:
  #     - /home/server/.config/prowlarr:/config
  #   restart: unless-stopped
