#!/bin/sh

userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"
sysresources="/etc/X11/xinit/.Xresources"
sysmodmap="/etc/X11/xinit/.Xmodmap"

# NOTE: merge X resources and keymaps
[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# NOTE: source system xinit hooks.
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# TODO: Multiple keyboards on notebook
setxkbmap us -variant intl -option caps:escape

# TODO: wallpaper
# if [ -x "$HOME/.config/nitrogen/bg-random.sh" ]; then
#     "$HOME/.config/nitrogen/bg-random.sh" &
# fi
# Wallpaper
# if [ -x "$HOME/.config/i3/scripts/wallpaper.sh" ]; then
#     "$HOME/.config/i3/scripts/wallpaper.sh" &
# fi


picom &

# TODO: Xorg notification daemon replacement for swaync.
# command -v dunst >/dev/null 2>&1 && dunst &

exec i3
