
local zsh_profile_loaded_today=0
PROFILE_MARKER="/tmp/.zsh_profile_loaded_today"

if [[ ! -f "$PROFILE_MARKER" ]]; then
    touch "$PROFILE_MARKER"
    zmodload zsh/zprof
    zsh_profile_loaded_today=1
fi

# ignoring keybinded commands on history
setopt histignorespace
# always storing the navigation
setopt autopushd

# zsh autocomplete
autoload -Uz compinit
compinit -C  # enables caching of completions
fpath=(~/.zsh/plugins/zsh-completions/src $fpath)

# loading plugins
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# loading prompt
eval "$(starship init zsh)"
eval "$(atuin init zsh)"

source ~/.config/shell/aliases.sh

# using fd as default fzf finder (following links, including hidden files and excluding useless directories)
export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --follow \
  --exclude node_modules --exclude .git --exclude .cache --exclude .asdf --exclude .local --exclude .cargo \
  --exclude .config --exclude bin --exclude obj --exclude.zsh --exclude.nvm --exclude.vscode --exclude target \
  --exclude .github' 

# search the contents of every file
function search {
   rg -p "$@" -A 3 -B 3 --color=always | less -RMFXK
}

for file in ~/.config/shell/*.sh; do
    . "$file"
done

source ~/.config/shell/keybindings.sh

if [[ $zsh_profile_loaded_today -eq 1 ]]; then
    zprof > "$PROFILE_MARKER"

    nu -c "
    open /tmp/zprof.out | 
    lines | 
    parse --regex '^\\s*\\d+\\)\\s*(?P<calls>\\d+)\\s+[\\d\\.]+\\s*[\\d\\.]+\\s*[\\d\\.%]+\\s*(?P<latency>[\\d\\.]+)\\s*[\\d\\.]+\\s*(?P<percentage>[\\d\\.%]+)\\s*(?P<name>.*)' |
    uniq |
    update calls {|x| \$x.calls | into int } |
    update latency {|x| \$x.latency | into float } |
    update percentage {|x| \$x.percentage | str replace '%' '' | into float } |
    where latency > 3 |
    select name calls latency percentage
    "
fi
