#!/bin/bash

monitors=$(hyprctl monitors | grep '^Monitor' | sed -E 's/^Monitor\s+([^ ]+)\s+\(.*$/\1/' | sort -r)
monitor_config="$HOME/.config/hypr/_monitors.conf"
workspaces_config="$HOME/.config/hypr/_workspaces.conf"

primary_monitor=""
second_monitor=""
third_monitor=""

function push_monitor() {
    local curr_monitor=$1

    if [ ! -z $primary_monitor ]; then
        if [ -z $second_monitor ]; then
            third_monitor=$second_monitor
        fi
        second_monitor=$primary_monitor
    fi

    primary_monitor=$curr_monitor
}

function unshift_monitor() {
    local curr_monitor=$1

    if [ -z $primary_monitor ]; then
        primary_monitor=$curr_monitor
    elif [ -z $second_monitor ]; then
        second_monitor=$curr_monitor
    else
        third_monitor=$curr_monitor
    fi
}

monitor_count=${#monitors[@]}

echo "# automatic generated by 'monitors_and_workspaces.sh'" > $monitor_config
for monitor in ${monitors[@]}
do
    if [[ "$monitor" == *"eDP"* ]]; then
        unshift_monitor $monitor
        echo "monitor=$monitor, preferred, auto, 1.333" >> $monitor_config
    else
        push_monitor "$monitor"
        echo "monitor=$monitor, preferred, auto, 1"  >> $monitor_config
    fi
done

# NOTE: each value is the prefered monitor when we have 1, 2 and 3 monitors
declare -A workspaces=(
    ["name:main"]="1,1,1"
    ["name:web"]="1,1,1"
    ["name:chat"]="1,2,2"
    ["name:log"]="1,1,1"
    ["name:aux"]="1,2,1"
    ["name:git"]="1,1,1"
    ["name:media"]="1,2,3"
    ["name:docs"]="1,1,1"
    ["name:game"]="1,1,1"
    ["name:steam"]="1,1,1"
    ["name:ps"]="1,2,2"
    ["name:stream"]="1,2,3"
)

echo "# automatic generated by 'monitors_and_workspaces.sh'" > $workspaces_config
for ws in "${!workspaces[@]}"; do
    preferred_monitor_idx=$(echo ${workspaces[$ws]} | cut -f 2 -d ",")
    case "$preferred_monitor_idx" in
        1) preferred_monitor=$primary_monitor
            ;;
        2) preferred_monitor=$second_monitor
            ;;
        *) preferred_monitor=$third_monitor
            ;;
    esac
    echo "Settings $ws on monitor $preferred_monitor..."
    echo "workspace = ${ws}, monitor:${preferred_monitor}" >> $workspaces_config

    # NOTE: ignoring error if workspace does not exit
    hyprctl dispatch moveworkspacetomonitor $ws $preferred_monitor || true
done

